[package]
name = "web_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "*"
scraper = "*"
tokio = { version = "*", features = ["full"] }
structopt = "*"
cssparser = "*"
kuchiki = "*"
selectors = "*"
itertools = "0.10.5"