[package]
name = "web_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "*"
reqwest = { version = "*", features = ["blocking", "json"] }
tokio = { version = "*", features = ["full"] }
url = "*"
scraper = "*"
